[package]
name = "bestiary"
version = "1.6.0-alpha.1"
description = "Some scary foes to fight."
edition.workspace = true
cairo-version.workspace = true

[dependencies]
starknet.workspace = true
dojo.workspace = true
dojo_macros.workspace = true

[dev-dependencies]
cairo_test = "2.11.4"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", rev = "4476c33" }

[lib]
