[package]
name = "dojo_examples"
description = "Dojo example to showcase Dojo features."
version = "1.7.0-alpha.1"	
edition = "2024_07"
cairo-version = "=2.11.4"
license = "MIT"

[cairo]
sierra-replace-ids = true

[dependencies]
openzeppelin = "0.20.0"
starknet = "2.11.4"

armory = { path = "../game-lib/armory" }
bestiary = { path = "../game-lib/bestiary" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.3" }
dojo_macros = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.3" }

[[target.starknet-contract]]
build-external-contracts = [
	"dojo::world::world_contract::world",
	"armory::m_Flatbow",
	"bestiary::m_RiverSkale",
]
allowed-libfuncs-list.name = "experimental"

[features]
default = ["dungeon"]
dungeon = []

[profile.saya]
