apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9300
    isDefault: true
    editable: true
    uid: prometheus
    jsonData:
      timeInterval: '5s'
      queryTimeout: '60s'
      httpMethod: 'GET'
