global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'torii-indexer'
    static_configs:
      - targets: ['host.docker.internal:9200']
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
