[alias]
generate-test-db = "run --manifest-path ./xtask/generate-test-db/Cargo.toml --"

# https://github.com/rust-lang/rust/issues/141626 (can be removed once link.exe is fixed)
[target.x86_64-pc-windows-msvc]
linker = "rust-lld"