[package]
name = "simple"
description = "simple"
version = "1.7.0"	
edition = "2024_07"
cairo-version = "2.12"
license = "MIT"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.12"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.4" }
dojo_macros = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.4" }

[[target.starknet-contract]]
